version: 2

build:
  image: testing

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true