#!/usr/bin/env python3

from __future__ import annotations
import os

import subprocess as sbp
import sys
import venv
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from types import SimpleNamespace

DEFAULT_PROMPT = "Cordy-Env"

class CordyEnvBuilder(venv.EnvBuilder):
    def __init__(self, system_site_packages: bool = False, clear: bool = False,
                 symlinks: bool = False, upgrade: bool = False,
                 prompt: str | None = None, upgrade_deps: bool = False) -> None:

        if sys.version_info < (3, 9):
            raise Exception(
                "Cordy environments must use python 3.9 or above."
                "\nLatest cpython is available at https://www.python.org/downloads/"
            )

        super().__init__(
            system_site_packages=system_site_packages,
            clear=clear, symlinks=symlinks, upgrade=upgrade,
            with_pip=True, prompt=prompt or DEFAULT_PROMPT,
            upgrade_deps=upgrade_deps
        )

    def create(self, env_dir): # Copied
        env_dir = os.path.abspath(env_dir)
        context = self.ensure_directories(env_dir)
        # See issue 24875. We need system_site_packages to be False
        # until after pip is installed.
        true_system_site_packages = self.system_site_packages
        self.system_site_packages = False
        self.create_configuration(context)
        self.setup_python(context)
        if self.with_pip:
            self._setup_pip(context)
        if not self.upgrade:
            self.setup_scripts(context)
            self.post_setup(context)
        if true_system_site_packages:
            # We had set it to False before, now
            # restore it and rewrite the configuration
            self.system_site_packages = True
            self.create_configuration(context)
        if self.upgrade_deps:
            self.upgrade_dependencies(context)
        self.setup_project_deps(context)

    def setup_project_deps(self, context: SimpleNamespace) -> None:
        cmd = [context.env_exe, "-m"]
        print(cmd)

        sys.stdout.write("Installing Poetry...\n")
        sys.stdout.write("=========\n")

        sbp.run(cmd + "pip install poetry --upgrade".split(), stderr=sbp.STDOUT)
        sys.stdout.write("=========\n")
        sys.stdout.write("Installing Cordy dependecies...\n")
        sys.stdout.write("=========\n")

        try:
            sbp.run(cmd + "poetry update".split(), check=True)
        except sbp.CalledProcessError as err:
            sys.stdout.write(f"Poetry failed with error code {err.returncode}\n")
            sys.stdout.write("Attempting cordy install instead ...\n")

            try:
                sbp.run(cmd + "poetry install".split(), check=True)
            except sbp.CalledProcessError as err:
                sys.stdout.write(f"Poetry failed with error code {err.returncode}\n")
                sys.stdout.write("Broken poetry install detected\n")

        sys.stdout.write("=========\n")

def main(argv=None) -> int:
    import argparse
    import os

    parser = argparse.ArgumentParser(prog="Cordy-venv",
                                        description='Creates virtual Python '
                                                    'environments in one or '
                                                    'more target '
                                                    'directories.',
                                        epilog='Once an environment has been '
                                            'created, you may wish to '
                                            'activate it, e.g. by '
                                            'sourcing an activate script '
                                            'in its bin directory.')
    parser.add_argument('dirs', metavar='ENV_DIR', nargs='+',
                        help='A directory to create the environment in.')
    parser.add_argument('--system-site-packages', default=False,
                        action='store_true', dest='system_site',
                        help='Give the virtual environment access to the '
                                'system site-packages dir.')
    if os.name == 'nt':
        use_symlinks = False
    else:
        use_symlinks = True

    group = parser.add_mutually_exclusive_group()
    group.add_argument('--symlinks', default=use_symlinks,
                        action='store_true', dest='symlinks',
                        help='Try to use symlinks rather than copies, '
                            'when symlinks are not the default for '
                            'the platform.')
    group.add_argument('--copies', default=not use_symlinks,
                        action='store_false', dest='symlinks',
                        help='Try to use copies rather than symlinks, '
                            'even when symlinks are the default for '
                            'the platform.')
    parser.add_argument('--clear', default=False, action='store_true',
                        dest='clear', help='Delete the contents of the '
                                            'environment directory if it '
                                            'already exists, before '
                                            'environment creation.')
    parser.add_argument('--upgrade', default=False, action='store_true',
                        dest='upgrade', help='Upgrade the environment '
                                            'directory to use this version '
                                            'of Python, assuming Python '
                                            'has been upgraded in-place.')
    parser.add_argument('--prompt',
                        help='Provides an alternative prompt prefix for '
                                'this environment.')
    parser.add_argument('--upgrade-deps', default=False, action='store_true',
                        dest='upgrade_deps')
    options = parser.parse_args(argv)

    if options.upgrade and options.clear:
        raise ValueError('you cannot supply --upgrade and --clear together.')

    builder = CordyEnvBuilder(
        system_site_packages=options.system_site,
        clear=options.clear,
        symlinks=options.symlinks,
        upgrade=options.upgrade,
        prompt=options.prompt,
        upgrade_deps=options.upgrade_deps
    )

    try:
        for d in options.dirs:
            builder.create(d)
    except Exception:
        import traceback
        traceback.print_exc()
        return 1
    else:
        return 0

if __name__ == "__main__":
    sys.exit(main())